### ISSUE TITLE
Option for limiting the number of workers?

### ISSUE THREAD

**Issue by fsouza** [nexe/resolve-dependencies#1]
Hey there, thanks for creating this project, it's really cool and extremely helpful.

We're trying to use nexe to bundle some of our tools and we're running into an issue when using it inside a container: the container runs out of memory due to the number of processes spawned (the host machine has 72 cores).

As you can see in nodejs/node#28765 and nodejs/node#28855, node's os.cpus doesn't really query the correct location on Linux and therefore can't get the number of available CPUs, so even though we're actually running the container with only 2 cores, nexe/resolve-dependencies still assumes 72 cores are available.

Would you be open to introducing an option in nexe and resolve-dependencies to limit the number of children spawned by the dependency resolution process? Or perhaps use a namespace-aware library for querying the number of available CPUs?

Thanks!

**Comment by calebboyd** [comment]
Available in `3.0.3` by setting RESOLVE_DEPENDENCIES_CPUS environment variable.

**Comment by fsouza** [comment]
@calebboyd ohhh my bad, thankssss
